{{ if eq .Values.ingress.type "standard" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- if .Values.services.nginx.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.services.nginx.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  creationTimestamp: null
  labels:
    app.service: {{ .Values.resourcePrefix }}nginx
  name: {{ .Values.resourcePrefix }}nginx
spec:
  {{- with (pick .Values.services.nginx.ingress "ingressClassName" "tls") }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  rules:
  - host: {{ index .Values.services "nginx" "environment" "APP_HOST" }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.resourcePrefix }}nginx
            port:
              number: 80
status:
  loadBalancer: {}
{{ end }}
