{{- if .Values.prometheus.podMonitoring -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.resourcePrefix }}nginx
  labels:
    app.service: {{ .Values.resourcePrefix }}nginx
spec:
  selector:
    matchLabels:
      app.service: {{ .Values.resourcePrefix }}nginx
  podMetricsEndpoints:
{{- if .Values.services.nginx.metricsEnabled -}}
{{ .Values.services.nginx.metricsEndpoints | toYaml | nindent 6 -}}
{{- end -}}
{{- end -}}
