{% include 'docker/image/console/Dockerfile.twig' %}

FROM console as node
COPY .my127ws/docker/image/app/root-node /

FROM {{ @('services.app.build.from.nginx') }} as nginx

RUN apk add --no-cache jq

COPY .my127ws/docker/image/app/root-nginx /
COPY config.jq /root/
COPY --from=node --chown=root:root {{ @('app.dist_path') }} /usr/share/nginx/html

ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["nginx", "-g", "daemon off;"]
